#!/bin/sh
#
# Kernel post-install hook for updating symlinks.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

# update for initramfs
if [ "$(readlink -q boot/initramfs.img)" != "initramfs-${VERSION}.img" ]
then
	echo "Updating initramfs.img..."
	mv -f boot/initramfs.img boot/initramfs-fallback.img
	ln -rsf "boot/initramfs-${VERSION}.img" boot/initramfs.img  
fi

# update for vmlinuz
if [ "$(readlink -q boot/vmlinuz)" != "vmlinuz-${VERSION}" ]
then
	echo "Updating vmlinuz..."
	mv -f boot/vmlinuz boot/vmlinuz-fallback
	ln -rsf "boot/vmlinuz-${VERSION}" /boot/vmlinuz
fi
